### ISSUE TITLE
Sync check incomplete notifications

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest-iac#343]
**Issue summary**

On a certain failure in the sync check, we don't get any logs on the Slack channel, just the failure notification.

<img width="452" alt="image" src="https://github.com/ChainSafe/forest-iac/assets/9642092/adb6b0ff-1797-4b90-a808-1e432988151a">

This is not optimal as it forces SSHing into the sync machine (which may be gone, along with the logs).

The `forest-tester` container has some errors that may indicate the culprit
```
root@forest-sync-check:~# docker logs forest-tester
/volumes/sync_check/sync_check.rb:18: warning: already initialized constant SLACK_TOKEN
/volumes/sync_check/sync_check_process.rb:12: warning: previous definition of SLACK_TOKEN was here
/volumes/sync_check/sync_check.rb:19: warning: already initialized constant CHANNEL
/volumes/sync_check/sync_check_process.rb:13: warning: previous definition of CHANNEL was here
/volumes/sync_check/sync_check.rb:18: warning: already initialized constant SLACK_TOKEN
/volumes/sync_check/sync_check_process.rb:12: warning: previous definition of SLACK_TOKEN was here
/volumes/sync_check/sync_check.rb:19: warning: already initialized constant CHANNEL
/volumes/sync_check/sync_check_process.rb:13: warning: previous definition of CHANNEL was here
D, [2023-11-14T13:18:30.435875 #7] DEBUG -- : Running `forest-tool` command with db destroy --chain mainnet --force
/usr/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - docker (Errno::ENOENT)
        from /usr/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from /usr/lib/ruby/3.0.0/open3.rb:102:in `popen3'
        from /usr/lib/ruby/3.0.0/open3.rb:289:in `capture3'
        from /volumes/sync_check/sync_check_process.rb:28:in `run_forest_container'
        from /volumes/sync_check/sync_check_process.rb:41:in `run_forest_tool'
        from /volumes/sync_check/sync_check.rb:54:in `<main>'
```

I believe this is incorrect:
https://github.com/ChainSafe/forest-iac/blob/1c38f2d4f31d9a6dc68b79a88c816628eace6015/terraform/modules/sync_check/service/sync_check.rb#L54

The way I see it:
1. There should be a `rescue` block to send Slack messages with logs even in case of an exception.
2. The `SyncCheck.new` should get the `client` injected as dependency, not re-created.
3. Not sure how `docker` is not present, but this should be investigated and resolved as well.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
Needless to say, let's also fix the underlying issue so that it doesn't happen or is adequately handled.
